# Generated by Django 4.2.11 on 2024-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='image_url',
        ),
        migrations.AddField(
            model_name='flan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
